name: 'General Testing'
on:
  - push
  - pull_request

permissions:
  contents: read
  pull-requests: read

jobs:
  test_wasm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12.3"
          cache: "pip"
      - run: |
          pip install pyodide-build==0.27.3
      - uses: mymindstorm/setup-emsdk@v14
        with:
          version: 3.1.58
      - run: pyodide build
      - run: |
          pyodide venv .venv-pyodide
          source .venv-pyodide/bin/activate
          pip install pytest dist/$(ls dist)
          pytest
